### PR TITLE
docs:fix language issues in document

### PR DESCRIPTION
**Pull request by blue-troy**
Signed-off-by: blue-troy <12729455+blue-troy@users.noreply.github.com>

fix language issues in document

## Description

fix language issues in document,such as active spelled as ative

## Related Issue

link #257

### CODE REVIEW

**Comment by dxsup** [comment]
Welcome to the kindling community and thanks for your contribution. I found that there are still some other issues in these documents. Would you mind if I corrected those in this PR? Or I will open another PR after merging yours.

**Comment by blue-troy** [comment]
> Welcome to the kindling community and thanks for your contribution. I found that there are still some other issues in these documents. Would you mind if I corrected those in this PR? Or I will open another PR after merging yours.

does other issues language problem?

**Comment by dxsup** [comment]
Yes. Some examples in `CONTRIBUTING.md` are as follows.
> Thank you for you(-> [**your**]) interest in contributing to kindling!

> you(-> [**You**]) can contribute to Kindling in several ways,(->[, ])like:

> l(-> [-]) Contribute to the codebase
l(-> [-]) Report and triage bugs
l(-> [-]) Write technical documentation and blog posts, for users and contributors
l(-> [-]) Help others by answering questions about Kindling

> [Report a bug](https://github.com/Kindling-project/kindling/issues/new?assignees=&labels=&template=bug_report.md&title=) by submitting a new issue. Make sure follow(-> [**to follow**]) the issue template and add more detail(-> [**detailed**]) informations(-> [**information**]) that will help us replicate the problem.

I can help correct these issues in this PR if you don't mind.

**Comment by blue-troy** [comment]
> Yes. Some examples in `CONTRIBUTING.md` are as follows.
> 
> > Thank you for you(-> [**your**]) interest in contributing to kindling!
> 
> > you(-> [**You**]) can contribute to Kindling in several ways,(->[, ])like:
> 
> > l(-> [-]) Contribute to the codebase
> > l(-> [-]) Report and triage bugs
> > l(-> [-]) Write technical documentation and blog posts, for users and contributors
> > l(-> [-]) Help others by answering questions about Kindling
> 
> > [Report a bug](https://github.com/Kindling-project/kindling/issues/new?assignees=&labels=&template=bug_report.md&title=) by submitting a new issue. Make sure follow(-> [**to follow**]) the issue template and add more detail(-> [**detailed**]) informations(-> [**information**]) that will help us replicate the problem.
> 
> I can help correct these issues in this PR if you don't mind.

OK

**Comment by dxsup** [comment]
@blue-troy 
I have corrected other issues found in the docs. Please take a look and we'll merge this PR after receiving your response.

**Comment by blue-troy** [comment]
> @blue-troy I have corrected other issues found in the docs. Please take a look and we'll merge this PR after receiving your response.

OK,and i change Github to GitHub

**Review by dxsup — APPROVED** [review]

**Pull request merged**
