### PR TITLE
Support automatic selection of whether to load kprobe

### PR DESCRIPTION
**Pull request by jundizhou**
Signed-off-by: jundizhou <jundizhou@harmonycloud.cn>

### CODE REVIEW

**Comment by sanyangji** [comment]
I review the code of agent-libs, the name SCAP_UNKNOW_KPROBE cannot be used for the program type of tracepoint (scap_bpf.c, line: 649, 837). I think some name like SCAP_LOAD_FAILED may be better.
Besides, UNKNOW should be UNKNOWN.
Others: format for scap_bpf.c:839: redundant blank before delimiter.

For this commit, I think the update aims to tolerate some errors of loading kprobe programs, changing the title may be better. Besides, I wonder if the program will output error info when skip loading kprobe programs

**Comment by jundizhou** [comment]
我会修改unknow->unkown，代码逻辑只有kprobe会返回这个类型。

**Comment by sanyangji** [comment]
> 我会修改unknow->unkown，代码逻辑只有kprobe会返回这个类型。

looks like tracepoint may reach this branch. [scap_bpf.c](https://github.com/jundizhou/agent-libs-1/blob/679965f63c25543967a0dba1b3f6c04325328657/userspace/libscap/scap_bpf.c#L649)

**Review by sanyangji — DISMISSED** [review]

**Comment by dxsup** [comment]
Please update the changelog. I suggest this as an enhancement.

**Review by dxsup — APPROVED** [review]

**Pull request merged**
